// Generated by https://quicktype.io

class Frase {
  int? quoteId;
  String? quote;
  String? author;
  String? series;

  Frase(
    this.quoteId,
    this.quote,
    this.author,
    this.series,
  );

  get getQuoteId => this.quote;
  get getQuote => this.quote;
  get getAuthor => this.author;
  get getSeries => this.series;

  //get Data json
  factory Frase.fromJSON(Map<String, dynamic> json) {
    return Frase(
        int.parse(json['quote_id'].toString()),
        json['quote'].toString(),
        json['author'].toString(),
        json['series'].toString());
  }
}
