// Generated by https://quicktype.io

class Muerto {
  int? deathId;
  String? death;
  String? cause;
  String? responsible;
  String? lastWords;
  int? season;
  int? episode;
  int? numberOfDeaths;

  Muerto(
    this.deathId,
    this.death,
    this.cause,
    this.responsible,
    this.lastWords,
    this.season,
    this.episode,
    this.numberOfDeaths,
  );

  get getDeathId => this.deathId;
  get getDeath => this.death;
  get getCause => this.cause;
  get getResponsible => this.responsible;
  get getLastWords => this.lastWords;
  get getSeason => this.season;
  get getEpisode => this.episode;
  get getNumerOfDeaths => this.numberOfDeaths;

  factory Muerto.fromJSON(Map<String, dynamic> json) {
    return Muerto(
      int.parse(json['death_id'].toString()),
      json['death'].toString(),
      json['cause'],
      json['responsible'],
      json['last_words'],
      json['season'],
      json['episode'],
      json['number_of_deaths'],
    );
  }
}
