// Generated by https://quicktype.io

class Post {
  int? userId;
  int? id;
  String? title;
  String? body;

  //borrar los corchetas que te genera
  //el plugin de pastjsoncode

  Post(
    this.userId,
    this.id,
    this.title,
    this.body,
  );

  get getuUerId => this.userId;
  get getId => this.id;
  get getTitle => this.title;
  get getBody => this.body;

  set setUserId(int value) => this.userId;
  set setId(int value) => this.id;
  set setTitle(String value) => this.title;
  set setBody(String value) => this.body;

//get dDATA del json
  factory Post.fromJSON(Map<String, dynamic> json) {
    return Post(int.parse(json['userId'].toString()),
        int.parse(json['id'].toString()), json['title'], json['body']);
  }

  //este metodo es para hacer un post o insert
  //basicamente para insertar variables al json desde la app
  Map<String, dynamic> toJSON() {
    return {
      'userId': this.userId,
      'id': this.id,
      'title': this.title,
      'body': this.body
    };
  }
}
